-- =============================================================
-- Dulceria Production — rename Collections to Variants
-- Migration 0047: pure rename, no behavior change
-- =============================================================
--
-- Why
--   The product "Collections" concept is being renamed to "Variants"
--   so the name "Collections" becomes free for a future, different
--   feature. Keep every row, every FK, every policy — just rename
--   tables and the `collectionId` FK column.
--
-- Renames
--   tables:
--     collections                 -> variants
--     collectionProducts          -> variantProducts
--     collectionPackagings        -> variantPackagings
--     collectionPricingSnapshots  -> variantPricingSnapshots
--   columns (on the three join/child tables):
--     collectionId                -> variantId
--
-- FK constraints auto-track table renames (ALTER TABLE RENAME rewires
-- the catalog). Indexes keep working but carry the old table name in
-- their identifiers — we rename those for readability / grep sanity.
--
-- Idempotent: guards every rename behind a pg_class / pg_attribute
-- existence check, so re-running is safe.
-- =============================================================

-- ---------- Tables ----------

do $$
begin
  if exists (select 1 from pg_class where relname = 'collections' and relnamespace = 'public'::regnamespace) then
    execute 'alter table public.collections rename to variants';
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class where relname = 'collectionProducts' and relnamespace = 'public'::regnamespace) then
    execute 'alter table public."collectionProducts" rename to "variantProducts"';
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class where relname = 'collectionPackagings' and relnamespace = 'public'::regnamespace) then
    execute 'alter table public."collectionPackagings" rename to "variantPackagings"';
  end if;
end $$;

do $$
begin
  if exists (select 1 from pg_class where relname = 'collectionPricingSnapshots' and relnamespace = 'public'::regnamespace) then
    execute 'alter table public."collectionPricingSnapshots" rename to "variantPricingSnapshots"';
  end if;
end $$;

-- ---------- Columns ----------

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'variantProducts'
      and column_name = 'collectionId'
  ) then
    execute 'alter table public."variantProducts" rename column "collectionId" to "variantId"';
  end if;
end $$;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'variantPackagings'
      and column_name = 'collectionId'
  ) then
    execute 'alter table public."variantPackagings" rename column "collectionId" to "variantId"';
  end if;
end $$;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'variantPricingSnapshots'
      and column_name = 'collectionId'
  ) then
    execute 'alter table public."variantPricingSnapshots" rename column "collectionId" to "variantId"';
  end if;
end $$;

-- ---------- Indexes (rename for consistency; autogenerated names
-- embed the old table name) ----------

do $$
declare
  r record;
begin
  for r in
    select indexname
    from pg_indexes
    where schemaname = 'public'
      and indexname like 'collection%'
  loop
    execute format(
      'alter index public.%I rename to %I',
      r.indexname,
      replace(replace(r.indexname, 'collectionPricingSnapshots', 'variantPricingSnapshots'),
              'collection', 'variant')
    );
  end loop;
end $$;

-- ---------- Schema cache ----------
-- PostgREST caches the schema; force a reload so new table/column names
-- are visible immediately (otherwise first request after deploy 404s).
notify pgrst, 'reload schema';
